version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: php_server
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - mongo
    networks:
      - backend
    environment:
      - PHP_EXTENSION=mysqli
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  

  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - backend

networks:
  backend:
